export const dicionario = new Map([
    ["Amor", [
        "Sentimento que induz a aproximar, a proteger ou a conservar a pessoa pela qual se sente afeição ou atração.",
        "Afeição acentuada por algo; grande dedicação ou zelo.",
        "Sentimento de afeto intenso que une duas pessoas; paixão."
      ]],
      ["Amizade", [
        "Sentimento de grande afeição, simpatia e apreço entre pessoas.",
        "Pacto ou acordo de não agressão entre nações."
      ]],
      ["Casa", [
        "Edifício de um ou mais andares, destinado a habitação; moradia, lar.",
        "Estabelecimento comercial ou de convívio.",
        "Cada uma das divisões de um tabuleiro de xadrez ou de damas."
      ]],
      ["Tempo", [
        "Período contínuo no qual os eventos se sucedem.",
        "Época determinada; momento.",
        "As condições atmosféricas; clima."
      ]],
      ["Vida", [
        "Conjunto de propriedades e qualidades graças às quais animais e plantas se mantêm em contínua atividade.",
        "O período que decorre entre o nascimento e a morte.",
        "Modo de viver; existência."
      ]],
      ["Trabalho", [
        "Atividade coordenada, de caráter físico e/ou intelectual, necessária à realização de qualquer tarefa.",
        "Ocupação remunerada; emprego.",
        "Obra realizada; resultado de uma atividade."
      ]],
      ["Cidade", ["Aglomerado urbano, geralmente de grande população, com uma infraestrutura desenvolvida."]],
      ["País", ["Nação politicamente organizada, com território definido e governo próprio."]],
      ["Mundo", [
        "O planeta Terra.",
        "O conjunto de tudo que existe; universo.",
        "Sociedade humana; conjunto de pessoas."
      ]],
      ["Pessoa", ["Indivíduo da espécie humana.", "Personagem; figura."]],
      ["Família", ["Conjunto de pessoas, em geral ligadas por laços de parentesco, que vivem sob o mesmo teto."]],
      ["Escola", ["Instituição destinada ao ensino coletivo.", "Conjunto de discípulos de um mestre; corrente de pensamento."]],
      ["Livro", [
        "Conjunto de folhas de papel, em branco, escritas ou impressas, reunidas em volume.",
        "Obra literária, científica ou artística que compõe um volume."
      ]],
      ["Comida", ["Qualquer substância que serve de alimento."]],
      ["Água", ["Líquido transparente, incolor, inodoro e insípido, essencial para a vida."]],
      ["Sol", ["Estrela central do nosso sistema solar.", "Luz e calor provenientes dessa estrela."]],
      ["Lua", ["Satélite natural da Terra."]],
      ["Natureza", ["Conjunto de tudo o que existe no universo e que não é produzido pelo ser humano.", "A essência ou índole de algo ou alguém."]],
      ["Arte", [
        "Atividade humana ligada a manifestações de ordem estética ou comunicativa.",
        "Habilidade ou técnica para fazer algo."
      ]],
      ["Cultura", [
        "Conjunto de manifestações artísticas, sociais, linguísticas e comportamentais de um povo.",
        "Conhecimento adquirido; instrução, saber."
      ]],
      ["História", [
        "Ciência que estuda os acontecimentos do passado relativos ao homem e à sociedade.",
        "Narrativa de acontecimentos reais ou fictícios; relato."
      ]],
      ["Ciência", ["Conhecimento atento e aprofundado de alguma coisa.", "Saber adquirido pela observação, pesquisa e experimentação."]],
      ["Tecnologia", ["Conjunto de conhecimentos e princípios científicos que se aplicam a um determinado ramo de atividade."]],
      ["Saúde", ["Estado de completo bem-estar físico, mental e social.", "Condição de bom funcionamento do organismo."]],
      ["Felicidade", ["Estado de quem é feliz; contentamento, bem-estar."]],
      ["Tristeza", ["Estado afetivo caracterizado pela falta de alegria, de ânimo."]],
      ["Medo", ["Sentimento de grande inquietação ante a noção de um perigo real ou imaginário."]],
      ["Coragem", ["Firmeza de espírito para enfrentar situação emocional ou moralmente difícil.", "Bravura, intrepidez."]],
      ["Força", [
        "Capacidade de exercer grande pressão ou de resistir a ela; vigor físico.",
        "Poder, influência, autoridade.",
        "Intensidade, energia."
      ]],
      ["Paz", ["Estado de tranquilidade e ausência de conflitos ou violência."]],
      ["Belo", ["Que tem beleza ou encanto; bonito, lindo."]],
      ["Grande", ["De dimensões ou tamanho superiores à média.", "Importante, notável, ilustre."]],
      ["Pequeno", ["De dimensões ou tamanho inferiores à média."]],
      ["Bom", [
        "Que tem as qualidades que lhe são atribuídas ou que se esperam.",
        "Agradável, benéfico, favorável."
      ]],
      ["Mau", ["Que não tem as qualidades desejáveis; ruim.", "Nocivo, prejudicial."]],
      ["Feliz", ["Que tem ou sente felicidade."]],
      ["Triste", ["Que sente ou revela tristeza."]],
      ["Inteligente", ["Que tem grande capacidade de compreender, aprender e raciocinar."]],
      ["Forte", ["Que tem força física ou moral."]],
      ["Fraco", ["Que tem pouca força; débil."]],
      ["Rápido", ["Que se move ou age com velocidade."]],
      ["Lento", ["Que se move ou age com vagareza."]],
      ["Novo", ["Que existe há pouco tempo; recente.", "Que ainda não foi usado; inédito."]],
      ["Velho", ["Que existe há muito tempo; antigo."]],
      ["Fácil", ["Que não exige grande esforço ou trabalho."]],
      ["Difícil", ["Que não é fácil; complicado, trabalhoso."]],
      ["Claro", ["Que tem ou recebe muita luz.", "De fácil compreensão; evidente."]],
      ["Escuro", ["Que tem falta ou ausência de luz."]],
      ["Certo", ["Que não admite dúvida; exato, correto.", "Algum, um determinado."]],
      ["Errado", ["Que não está certo; incorreto."]],
      ["Quente", ["Que tem ou produz calor."]],
      ["Frio", ["Que tem baixa temperatura."]],
      ["Rico", ["Que possui muitos bens materiais ou dinheiro."]],
      ["Pobre", ["Que não tem o necessário para viver.", "Carente, desprovido de algo."]],
      ["Limpo", ["Que não tem sujeira."]],
      ["Sujo", ["Que não está limpo."]],
      ["Alto", ["Que tem grande extensão vertical.", "De som agudo; elevado."]],
      ["Baixo", ["Que tem pouca extensão vertical.", "De som grave."]],
      ["Doce", ["Que tem sabor semelhante ao do açúcar.", "Meigo, suave, afável."]],
      ["Amargo", ["Que tem sabor acre, desagradável."]],
      ["Ser", ["Ter existência; existir, viver.", "Constituir a essência de algo."]],
      ["Estar", ["Encontrar-se em determinada situação ou estado.", "Permanecer em um lugar."]],
      ["Fazer", ["Realizar, executar, criar algo.", "Produzir, fabricar."]],
      ["Ir", ["Mover-se de um lugar para outro."]],
      ["Vir", ["Dirigir-se ou ser transportado para o lugar onde está quem fala."]],
      ["Ter", ["Possuir, dispor de.", "Sentir, experimentar (ter fome, ter sede)."]],
      ["Poder", ["Ter a capacidade ou a faculdade de fazer algo.", "Ter permissão para."]],
      ["Dizer", ["Expressar por palavras; falar."]],
      ["Falar", ["Comunicar-se por meio de palavras."]],
      ["Querer", ["Ter vontade de; desejar.", "Sentir afeto; amar."]],
      ["Saber", ["Ter conhecimento ou informação de.", "Ter habilidade para."]],
      ["Ver", ["Perceber pela visão; enxergar.", "Compreender, entender."]],
      ["Ouvir", ["Perceber pelos ouvidos; escutar."]],
      ["Comer", ["Ingerir como alimento."]],
      ["Beber", ["Ingerir líquido."]],
      ["Dormir", ["Estar no estado de sono, repousar."]],
      ["Acordar", ["Sair do sono; despertar."]],
      ["Trabalhar", ["Exercer alguma atividade profissional ou ofício."]],
      ["Estudar", ["Aplicar a inteligência para aprender algo."]],
      ["Aprender", ["Adquirir conhecimento ou habilidade."]],
      ["Ensinar", ["Transmitir conhecimento ou instrução a."]],
      ["Viver", ["Estar com vida; existir."]],
      ["Morrer", ["Deixar de viver; falecer."]],
      ["Amar", ["Sentir amor por alguém ou algo."]],
      ["Gostar", ["Sentir afeição, apreço ou prazer."]],
      ["Ajudar", ["Prestar auxílio ou socorro a."]],
      ["Começar", ["Dar início a; principiar."]],
      ["Terminar", ["Pôr termo a; acabar, concluir."]],
      ["Abrir", ["Remover o que veda uma abertura ou passagem.", "Iniciar, inaugurar."]],
      ["Fechar", ["Impedir a passagem através de uma abertura.", "Concluir, encerrar."]],
      ["Garfo", ["Utensílio de mesa com dentes para espetar alimentos sólidos."]],
      ["Faca", ["Instrumento cortante, composto por uma lâmina e um cabo."]],
      ["Colher", ["Utensílio de mesa ou de cozinha, côncavo, usado para levar alimentos líquidos ou pastosos à boca."]],
      ["Prato", ["Recipiente raso, geralmente circular, onde se serve a comida.", "A comida servida nesse recipiente."]],
      ["Copo", ["Pequeno recipiente, geralmente de vidro, sem asa, usado para beber líquidos."]],
      ["Xícara", ["Recipiente pequeno com asa, usado para tomar bebidas quentes como café ou chá."]],
      ["Panela", ["Recipiente de metal, geralmente com cabo ou asas, usado para cozinhar alimentos."]],
      ["Frigideira", ["Panela rasa, de cabo comprido, usada para fritar alimentos."]],
      ["Geladeira", ["Eletrodoméstico que refrigera e conserva alimentos e bebidas."]],
      ["Fogão", ["Aparelho de cozinha utilizado para aquecer ou cozinhar alimentos."]],
      ["Micro-ondas", ["Forno elétrico que utiliza radiação eletromagnética para aquecer alimentos rapidamente."]],
      ["Liquidificador", ["Aparelho elétrico usado para misturar, triturar ou liquefazer alimentos."]],
      ["Torradeira", ["Pequeno eletrodoméstico usado para tostar fatias de pão."]],
      ["Ralador", ["Utensílio com superfície perfurada e áspera, usado para ralar alimentos."]],
      ["Abridor de latas", ["Ferramenta utilizada para abrir latas de metal."]],
      ["Sofá", ["Móvel estofado com encosto e braços, para duas ou mais pessoas se sentarem."]],
      ["Cadeira", ["Assento com encosto para uma só pessoa."]],
      ["Mesa", ["Móvel composto por um tampo plano suportado por pernas, usado para refeições, trabalho, etc."]],
      ["Cama", ["Móvel sobre o qual se dorme, geralmente composto por um estrado e um colchão."]],
      ["Travesseiro", ["Almofada macia usada para apoiar a cabeça ao dormir."]],
      ["Cobertor", ["Peça de tecido grosso e quente usada para se cobrir na cama."]],
      ["Guarda-roupa", ["Móvel, geralmente um armário grande, onde se guardam roupas."]],
      ["Abajur", ["Luminária de mesa ou de chão com uma cúpula para suavizar a luz."]],
      ["Televisão", ["Aparelho eletrônico que recebe e exibe imagens e sons transmitidos."]],
      ["Cortina", ["Peça de tecido pendurada em janelas ou portas para bloquear a luz ou dar privacidade."]],
      ["Tapete", ["Peça de tecido grosso ou de outro material, usada para cobrir o chão."]],
      ["Espelho", ["Superfície polida, geralmente de vidro com uma camada de metal, que reflete imagens."]],
      ["Vaso", ["Recipiente, muitas vezes decorativo, usado para colocar plantas, flores ou como ornamento."]],
      ["Estante", ["Móvel com prateleiras para guardar livros, objetos, etc."]],
      ["Despertador", ["Relógio que emite um som em hora programada para acordar alguém."]],
      ["Caneta", ["Instrumento de escrita que contém um tubo de tinta."]],
      ["Lápis", ["Instrumento de escrita ou desenho feito de um bastão de grafite envolto em madeira."]],
      ["Borracha", ["Objeto usado para apagar o que foi escrito ou desenhado com lápis."]],
      ["Apontador", ["Pequeno instrumento usado para afiar a ponta de um lápis."]],
      ["Caderno", ["Conjunto de folhas de papel unidas, usado para escrever ou desenhar."]],
      ["Agenda", ["Livro ou caderno para anotar compromissos e tarefas diárias."]],
      ["Computador", ["Máquina eletrônica capaz de armazenar e processar dados."]],
      ["Mouse", ["Dispositivo periférico que permite interagir com a interface gráfica de um computador."]],
      ["Teclado", ["Conjunto de teclas usado para inserir dados em um computador ou outra máquina."]],
      ["Impressora", ["Máquina que imprime textos ou imagens de um computador em papel."]],
      ["Monitor", ["Tela que exibe as informações visuais de um computador."]],
      ["Grampeador", ["Aparelho que usa grampos para prender folhas de papel."]],
      ["Tesoura", ["Instrumento de corte com duas lâminas que se movem sobre um eixo comum."]],
      ["Régua", ["Instrumento plano com marcações de medida, usado para traçar linhas retas."]],
      ["Calculadora", ["Dispositivo eletrônico usado para realizar cálculos matemáticos."]],
      ["Mochila", ["Saco com alças para ser carregado nas costas, usado para transportar objetos pessoais."]],
      ["Clips", ["Pequeno objeto de metal ou plástico usado para prender papéis."]],
      ["Relógio", ["Instrumento que mede e indica as horas."]],
      ["Óculos", ["Objeto com lentes usado para corrigir a visão ou proteger os olhos."]],
      ["Carteira", ["Pequeno objeto, geralmente de couro, para guardar dinheiro, cartões e documentos."]],
      ["Chave", ["Instrumento de metal usado para abrir e fechar fechaduras."]],
      ["Guarda-chuva", ["Objeto portátil usado para se proteger da chuva ou do sol."]],
      ["Celular", ["Aparelho de telefonia móvel com múltiplas funções."]],
      ["Fone de ouvido", ["Dispositivo de áudio que se coloca nos ouvidos para escutar sons de forma privada."]],
      ["Chapéu", ["Acessório para cobrir a cabeça, para proteção ou adorno."]],
      ["Sapato", ["Calçado que cobre e protege o pé."]],
      ["Tênis", ["Tipo de calçado esportivo e casual."]],
      ["Bota", ["Calçado que cobre o pé e parte da perna."]],
      ["Sandália", ["Calçado aberto, preso ao pé por tiras."]],
      ["Meia", ["Peça de vestuário que cobre os pés."]],
      ["Calça", ["Peça de vestuário que cobre da cintura aos pés, separadamente para cada perna."]],
      ["Camisa", ["Peça de vestuário que cobre o tronco, geralmente com gola, mangas e botões."]],
      ["Camiseta", ["Peça de vestuário de malha e sem gola, para o tronco."]],
      ["Vestido", ["Peça de vestuário feminina de uma só peça que cobre o corpo da cintura para baixo."]],
      ["Saia", ["Peça de vestuário que pende da cintura para baixo."]],
      ["Casaco", ["Peça de vestuário usada sobre outras para proteger do frio."]],
      ["Cinto", ["Tira de couro ou outro material usada para segurar as calças na cintura."]],
      ["Anel", ["Joia em forma de aro usada no dedo."]],
      ["Colar", ["Adorno usado ao redor do pescoço."]],
      ["Pulseira", ["Joia ou adorno usado no pulso."]],
      ["Brinco", ["Adorno usado na orelha."]],
      ["Martelo", ["Ferramenta para bater, pregar ou quebrar, composta por uma cabeça de metal e um cabo."]],
      ["Chave de fenda", ["Ferramenta com ponta achatada ou em cruz, usada para apertar ou soltar parafusos."]],
      ["Alicate", ["Ferramenta articulada usada para segurar, torcer, cortar ou dobrar objetos."]],
      ["Parafuso", ["Peça cônica ou cilíndrica com um sulco em espiral, usada para fixar objetos."]],
      ["Prego", ["Pequena haste de metal com ponta afiada e uma cabeça, usada para fixar objetos em madeira."]],
      ["Serrote", ["Ferramenta com lâmina dentada usada para cortar madeira."]],
      ["Escada", ["Estrutura com degraus que permite subir e descer entre diferentes níveis."]],
      ["Lanterna", ["Aparelho portátil de iluminação, geralmente a pilhas ou bateria."]],
      ["Vassoura", ["Utensílio de limpeza com um cabo longo e um feixe de pelos ou fibras na ponta."]],
      ["Balde", ["Recipiente com alça, geralmente em forma de cone truncado, para transportar líquidos ou outros materiais."]],
      ["Esponja", ["Material poroso, natural ou sintético, usado para limpeza ou banho."]],
      ["Sabonete", ["Produto de higiene pessoal usado para lavar as mãos e o corpo."]],
      ["Shampoo", ["Produto líquido usado para lavar os cabelos."]],
      ["Pente", ["Objeto com dentes finos usado para desembaraçar e arrumar os cabelos."]],
      ["Escova de dentes", ["Pequena escova usada com pasta para limpar os dentes."]],
      ["Toalha", ["Peça de tecido absorvente usada para secar o corpo, mãos ou rosto."]],
      ["Isqueiro", ["Pequeno dispositivo portátil que produz uma chama."]],
      ["Vela", ["Objeto de cera ou parafina com um pavio no centro, que fornece luz ao queimar."]],
      ["Bola", ["Objeto esférico usado em muitos jogos e esportes."]],
      ["Bicicleta", ["Veículo de duas rodas movido pela força dos pedais."]],
])