export const dicionario = new Map([
    ["Amor", [
        "Sentimento que induz a aproximar, a proteger ou a conservar a pessoa pela qual se sente afeição ou atração.",
        "Afeição acentuada por algo; grande dedicação ou zelo.",
        "Sentimento de afeto intenso que une duas pessoas; paixão."
      ]],
      ["Amizade", [
        "Sentimento de grande afeição, simpatia e apreço entre pessoas.",
        "Pacto ou acordo de não agressão entre nações."
      ]],
      ["Casa", [
        "Edifício de um ou mais andares, destinado a habitação; moradia, lar.",
        "Estabelecimento comercial ou de convívio.",
        "Cada uma das divisões de um tabuleiro de xadrez ou de damas."
      ]],
      ["Tempo", [
        "Período contínuo no qual os eventos se sucedem.",
        "Época determinada; momento.",
        "As condições atmosféricas; clima."
      ]],
      ["Vida", [
        "Conjunto de propriedades e qualidades graças às quais animais e plantas se mantêm em contínua atividade.",
        "O período que decorre entre o nascimento e a morte.",
        "Modo de viver; existência."
      ]],
      ["Trabalho", [
        "Atividade coordenada, de caráter físico e/ou intelectual, necessária à realização de qualquer tarefa.",
        "Ocupação remunerada; emprego.",
        "Obra realizada; resultado de uma atividade."
      ]],
      ["Cidade", ["Aglomerado urbano, geralmente de grande população, com uma infraestrutura desenvolvida."]],
      ["País", ["Nação politicamente organizada, com território definido e governo próprio."]],
      ["Mundo", [
        "O planeta Terra.",
        "O conjunto de tudo que existe; universo.",
        "Sociedade humana; conjunto de pessoas."
      ]],
      ["Pessoa", ["Indivíduo da espécie humana.", "Personagem; figura."]],
      ["Família", ["Conjunto de pessoas, em geral ligadas por laços de parentesco, que vivem sob o mesmo teto."]],
      ["Escola", ["Instituição destinada ao ensino coletivo.", "Conjunto de discípulos de um mestre; corrente de pensamento."]],
      ["Livro", [
        "Conjunto de folhas de papel, em branco, escritas ou impressas, reunidas em volume.",
        "Obra literária, científica ou artística que compõe um volume."
      ]],
      ["Comida", ["Qualquer substância que serve de alimento."]],
      ["Água", ["Líquido transparente, incolor, inodoro e insípido, essencial para a vida."]],
      ["Sol", ["Estrela central do nosso sistema solar.", "Luz e calor provenientes dessa estrela."]],
      ["Lua", ["Satélite natural da Terra."]],
      ["Natureza", ["Conjunto de tudo o que existe no universo e que não é produzido pelo ser humano.", "A essência ou índole de algo ou alguém."]],
      ["Arte", [
        "Atividade humana ligada a manifestações de ordem estética ou comunicativa.",
        "Habilidade ou técnica para fazer algo."
      ]],
      ["Cultura", [
        "Conjunto de manifestações artísticas, sociais, linguísticas e comportamentais de um povo.",
        "Conhecimento adquirido; instrução, saber."
      ]],
      ["História", [
        "Ciência que estuda os acontecimentos do passado relativos ao homem e à sociedade.",
        "Narrativa de acontecimentos reais ou fictícios; relato."
      ]],
      ["Ciência", ["Conhecimento atento e aprofundado de alguma coisa.", "Saber adquirido pela observação, pesquisa e experimentação."]],
      ["Tecnologia", ["Conjunto de conhecimentos e princípios científicos que se aplicam a um determinado ramo de atividade."]],
      ["Saúde", ["Estado de completo bem-estar físico, mental e social.", "Condição de bom funcionamento do organismo."]],
      ["Felicidade", ["Estado de quem é feliz; contentamento, bem-estar."]],
      ["Tristeza", ["Estado afetivo caracterizado pela falta de alegria, de ânimo."]],
      ["Medo", ["Sentimento de grande inquietação ante a noção de um perigo real ou imaginário."]],
      ["Coragem", ["Firmeza de espírito para enfrentar situação emocional ou moralmente difícil.", "Bravura, intrepidez."]],
      ["Força", [
        "Capacidade de exercer grande pressão ou de resistir a ela; vigor físico.",
        "Poder, influência, autoridade.",
        "Intensidade, energia."
      ]],
      ["Paz", ["Estado de tranquilidade e ausência de conflitos ou violência."]],
      ["Belo", ["Que tem beleza ou encanto; bonito, lindo."]],
      ["Grande", ["De dimensões ou tamanho superiores à média.", "Importante, notável, ilustre."]],
      ["Pequeno", ["De dimensões ou tamanho inferiores à média."]],
      ["Bom", [
        "Que tem as qualidades que lhe são atribuídas ou que se esperam.",
        "Agradável, benéfico, favorável."
      ]],
      ["Mau", ["Que não tem as qualidades desejáveis; ruim.", "Nocivo, prejudicial."]],
      ["Feliz", ["Que tem ou sente felicidade."]],
      ["Triste", ["Que sente ou revela tristeza."]],
      ["Inteligente", ["Que tem grande capacidade de compreender, aprender e raciocinar."]],
      ["Forte", ["Que tem força física ou moral."]],
      ["Fraco", ["Que tem pouca força; débil."]],
      ["Rápido", ["Que se move ou age com velocidade."]],
      ["Lento", ["Que se move ou age com vagareza."]],
      ["Novo", ["Que existe há pouco tempo; recente.", "Que ainda não foi usado; inédito."]],
      ["Velho", ["Que existe há muito tempo; antigo."]],
      ["Fácil", ["Que não exige grande esforço ou trabalho."]],
      ["Difícil", ["Que não é fácil; complicado, trabalhoso."]],
      ["Claro", ["Que tem ou recebe muita luz.", "De fácil compreensão; evidente."]],
      ["Escuro", ["Que tem falta ou ausência de luz."]],
      ["Certo", ["Que não admite dúvida; exato, correto.", "Algum, um determinado."]],
      ["Errado", ["Que não está certo; incorreto."]],
      ["Quente", ["Que tem ou produz calor."]],
      ["Frio", ["Que tem baixa temperatura."]],
      ["Rico", ["Que possui muitos bens materiais ou dinheiro."]],
      ["Pobre", ["Que não tem o necessário para viver.", "Carente, desprovido de algo."]],
      ["Limpo", ["Que não tem sujeira."]],
      ["Sujo", ["Que não está limpo."]],
      ["Alto", ["Que tem grande extensão vertical.", "De som agudo; elevado."]],
      ["Baixo", ["Que tem pouca extensão vertical.", "De som grave."]],
      ["Doce", ["Que tem sabor semelhante ao do açúcar.", "Meigo, suave, afável."]],
      ["Amargo", ["Que tem sabor acre, desagradável."]],
      ["Ser", ["Ter existência; existir, viver.", "Constituir a essência de algo."]],
      ["Estar", ["Encontrar-se em determinada situação ou estado.", "Permanecer em um lugar."]],
      ["Fazer", ["Realizar, executar, criar algo.", "Produzir, fabricar."]],
      ["Ir", ["Mover-se de um lugar para outro."]],
      ["Vir", ["Dirigir-se ou ser transportado para o lugar onde está quem fala."]],
      ["Ter", ["Possuir, dispor de.", "Sentir, experimentar (ter fome, ter sede)."]],
      ["Poder", ["Ter a capacidade ou a faculdade de fazer algo.", "Ter permissão para."]],
      ["Dizer", ["Expressar por palavras; falar."]],
      ["Falar", ["Comunicar-se por meio de palavras."]],
      ["Querer", ["Ter vontade de; desejar.", "Sentir afeto; amar."]],
      ["Saber", ["Ter conhecimento ou informação de.", "Ter habilidade para."]],
      ["Ver", ["Perceber pela visão; enxergar.", "Compreender, entender."]],
      ["Ouvir", ["Perceber pelos ouvidos; escutar."]],
      ["Comer", ["Ingerir como alimento."]],
      ["Beber", ["Ingerir líquido."]],
      ["Dormir", ["Estar no estado de sono, repousar."]],
      ["Acordar", ["Sair do sono; despertar."]],
      ["Trabalhar", ["Exercer alguma atividade profissional ou ofício."]],
      ["Estudar", ["Aplicar a inteligência para aprender algo."]],
      ["Aprender", ["Adquirir conhecimento ou habilidade."]],
      ["Ensinar", ["Transmitir conhecimento ou instrução a."]],
      ["Viver", ["Estar com vida; existir."]],
      ["Morrer", ["Deixar de viver; falecer."]],
      ["Amar", ["Sentir amor por alguém ou algo."]],
      ["Gostar", ["Sentir afeição, apreço ou prazer."]],
      ["Ajudar", ["Prestar auxílio ou socorro a."]],
      ["Começar", ["Dar início a; principiar."]],
      ["Terminar", ["Pôr termo a; acabar, concluir."]],
      ["Abrir", ["Remover o que veda uma abertura ou passagem.", "Iniciar, inaugurar."]],
      ["Fechar", ["Impedir a passagem através de uma abertura.", "Concluir, encerrar."]],
      ["Garfo", ["Utensílio de mesa com dentes para espetar alimentos sólidos."]],
      ["Faca", ["Instrumento cortante, composto por uma lâmina e um cabo."]],
      ["Colher", ["Utensílio de mesa ou de cozinha, côncavo, usado para levar alimentos líquidos ou pastosos à boca."]],
      ["Prato", ["Recipiente raso, geralmente circular, onde se serve a comida.", "A comida servida nesse recipiente."]],
      ["Copo", ["Pequeno recipiente, geralmente de vidro, sem asa, usado para beber líquidos."]],
      ["Xícara", ["Recipiente pequeno com asa, usado para tomar bebidas quentes como café ou chá."]],
      ["Panela", ["Recipiente de metal, geralmente com cabo ou asas, usado para cozinhar alimentos."]],
      ["Frigideira", ["Panela rasa, de cabo comprido, usada para fritar alimentos."]],
      ["Geladeira", ["Eletrodoméstico que refrigera e conserva alimentos e bebidas."]],
      ["Fogão", ["Aparelho de cozinha utilizado para aquecer ou cozinhar alimentos."]],
      ["Micro-ondas", ["Forno elétrico que utiliza radiação eletromagnética para aquecer alimentos rapidamente."]],
      ["Liquidificador", ["Aparelho elétrico usado para misturar, triturar ou liquefazer alimentos."]],
      ["Torradeira", ["Pequeno eletrodoméstico usado para tostar fatias de pão."]],
      ["Ralador", ["Utensílio com superfície perfurada e áspera, usado para ralar alimentos."]],
      ["Abridor de latas", ["Ferramenta utilizada para abrir latas de metal."]],
      ["Sofá", ["Móvel estofado com encosto e braços, para duas ou mais pessoas se sentarem."]],
      ["Cadeira", ["Assento com encosto para uma só pessoa."]],
      ["Mesa", ["Móvel composto por um tampo plano suportado por pernas, usado para refeições, trabalho, etc."]],
      ["Cama", ["Móvel sobre o qual se dorme, geralmente composto por um estrado e um colchão."]],
      ["Travesseiro", ["Almofada macia usada para apoiar a cabeça ao dormir."]],
      ["Cobertor", ["Peça de tecido grosso e quente usada para se cobrir na cama."]],
      ["Guarda-roupa", ["Móvel, geralmente um armário grande, onde se guardam roupas."]],
      ["Abajur", ["Luminária de mesa ou de chão com uma cúpula para suavizar a luz."]],
      ["Televisão", ["Aparelho eletrônico que recebe e exibe imagens e sons transmitidos."]],
      ["Cortina", ["Peça de tecido pendurada em janelas ou portas para bloquear a luz ou dar privacidade."]],
      ["Tapete", ["Peça de tecido grosso ou de outro material, usada para cobrir o chão."]],
      ["Espelho", ["Superfície polida, geralmente de vidro com uma camada de metal, que reflete imagens."]],
      ["Vaso", ["Recipiente, muitas vezes decorativo, usado para colocar plantas, flores ou como ornamento."]],
      ["Estante", ["Móvel com prateleiras para guardar livros, objetos, etc."]],
      ["Despertador", ["Relógio que emite um som em hora programada para acordar alguém."]],
      ["Caneta", ["Instrumento de escrita que contém um tubo de tinta."]],
      ["Lápis", ["Instrumento de escrita ou desenho feito de um bastão de grafite envolto em madeira."]],
      ["Borracha", ["Objeto usado para apagar o que foi escrito ou desenhado com lápis."]],
      ["Apontador", ["Pequeno instrumento usado para afiar a ponta de um lápis."]],
      ["Caderno", ["Conjunto de folhas de papel unidas, usado para escrever ou desenhar."]],
      ["Agenda", ["Livro ou caderno para anotar compromissos e tarefas diárias."]],
      ["Computador", ["Máquina eletrônica capaz de armazenar e processar dados."]],
      ["Mouse", ["Dispositivo periférico que permite interagir com a interface gráfica de um computador."]],
      ["Teclado", ["Conjunto de teclas usado para inserir dados em um computador ou outra máquina."]],
      ["Impressora", ["Máquina que imprime textos ou imagens de um computador em papel."]],
      ["Monitor", ["Tela que exibe as informações visuais de um computador."]],
      ["Grampeador", ["Aparelho que usa grampos para prender folhas de papel."]],
      ["Tesoura", ["Instrumento de corte com duas lâminas que se movem sobre um eixo comum."]],
      ["Régua", ["Instrumento plano com marcações de medida, usado para traçar linhas retas."]],
      ["Calculadora", ["Dispositivo eletrônico usado para realizar cálculos matemáticos."]],
      ["Mochila", ["Saco com alças para ser carregado nas costas, usado para transportar objetos pessoais."]],
      ["Clips", ["Pequeno objeto de metal ou plástico usado para prender papéis."]],
      ["Relógio", ["Instrumento que mede e indica as horas."]],
      ["Óculos", ["Objeto com lentes usado para corrigir a visão ou proteger os olhos."]],
      ["Carteira", ["Pequeno objeto, geralmente de couro, para guardar dinheiro, cartões e documentos."]],
      ["Chave", ["Instrumento de metal usado para abrir e fechar fechaduras."]],
      ["Guarda-chuva", ["Objeto portátil usado para se proteger da chuva ou do sol."]],
      ["Celular", ["Aparelho de telefonia móvel com múltiplas funções."]],
      ["Fone de ouvido", ["Dispositivo de áudio que se coloca nos ouvidos para escutar sons de forma privada."]],
      ["Chapéu", ["Acessório para cobrir a cabeça, para proteção ou adorno."]],
      ["Sapato", ["Calçado que cobre e protege o pé."]],
      ["Tênis", ["Tipo de calçado esportivo e casual."]],
      ["Bota", ["Calçado que cobre o pé e parte da perna."]],
      ["Sandália", ["Calçado aberto, preso ao pé por tiras."]],
      ["Meia", ["Peça de vestuário que cobre os pés."]],
      ["Calça", ["Peça de vestuário que cobre da cintura aos pés, separadamente para cada perna."]],
      ["Camisa", ["Peça de vestuário que cobre o tronco, geralmente com gola, mangas e botões."]],
      ["Camiseta", ["Peça de vestuário de malha e sem gola, para o tronco."]],
      ["Vestido", ["Peça de vestuário feminina de uma só peça que cobre o corpo da cintura para baixo."]],
      ["Saia", ["Peça de vestuário que pende da cintura para baixo."]],
      ["Casaco", ["Peça de vestuário usada sobre outras para proteger do frio."]],
      ["Cinto", ["Tira de couro ou outro material usada para segurar as calças na cintura."]],
      ["Anel", ["Joia em forma de aro usada no dedo."]],
      ["Colar", ["Adorno usado ao redor do pescoço."]],
      ["Pulseira", ["Joia ou adorno usado no pulso."]],
      ["Brinco", ["Adorno usado na orelha."]],
      ["Martelo", ["Ferramenta para bater, pregar ou quebrar, composta por uma cabeça de metal e um cabo."]],
      ["Chave de fenda", ["Ferramenta com ponta achatada ou em cruz, usada para apertar ou soltar parafusos."]],
      ["Alicate", ["Ferramenta articulada usada para segurar, torcer, cortar ou dobrar objetos."]],
      ["Parafuso", ["Peça cônica ou cilíndrica com um sulco em espiral, usada para fixar objetos."]],
      ["Prego", ["Pequena haste de metal com ponta afiada e uma cabeça, usada para fixar objetos em madeira."]],
      ["Serrote", ["Ferramenta com lâmina dentada usada para cortar madeira."]],
      ["Escada", ["Estrutura com degraus que permite subir e descer entre diferentes níveis."]],
      ["Lanterna", ["Aparelho portátil de iluminação, geralmente a pilhas ou bateria."]],
      ["Vassoura", ["Utensílio de limpeza com um cabo longo e um feixe de pelos ou fibras na ponta."]],
      ["Balde", ["Recipiente com alça, geralmente em forma de cone truncado, para transportar líquidos ou outros materiais."]],
      ["Esponja", ["Material poroso, natural ou sintético, usado para limpeza ou banho."]],
      ["Sabonete", ["Produto de higiene pessoal usado para lavar as mãos e o corpo."]],
      ["Shampoo", ["Produto líquido usado para lavar os cabelos."]],
      ["Pente", ["Objeto com dentes finos usado para desembaraçar e arrumar os cabelos."]],
      ["Escova de dentes", ["Pequena escova usada com pasta para limpar os dentes."]],
      ["Toalha", ["Peça de tecido absorvente usada para secar o corpo, mãos ou rosto."]],
      ["Isqueiro", ["Pequeno dispositivo portátil que produz uma chama."]],
      ["Vela", ["Objeto de cera ou parafina com um pavio no centro, que fornece luz ao queimar."]],
      ["Bola", ["Objeto esférico usado em muitos jogos e esportes."]],
      ["Bicicleta", ["Veículo de duas rodas movido pela força dos pedais."]],
      ["Alegria", ["Estado de viva satisfação e contentamento; júbilo, prazer."]],
      ["Esperança", ["Sentimento de quem espera que algo desejado aconteça.", "Confiança em coisa boa; fé."]],
      ["Saudade", ["Sentimento melancólico devido ao afastamento de uma pessoa, uma coisa ou um lugar."]],
      ["Liberdade", ["Direito de agir segundo o seu livre arbítrio.", "Estado de quem não é escravo ou prisioneiro."]],
      ["Justiça", ["Qualidade do que está em conformidade com o que é direito.", "O poder de fazer valer o direito de cada um."]],
      ["Conhecimento", ["Ato ou efeito de conhecer; posse de informações, saberes.", "Consciência da existência de algo."]],
      ["Sonho", ["Conjunto de ideias e imagens que se apresentam ao espírito durante o sono.", "Desejo vivo e constante; fantasia, utopia."]],
      ["Luz", ["Radiação eletromagnética que sensibiliza os olhos.", "Claridade, iluminação.", "Conhecimento, esclarecimento."]],
      ["Sombra", ["Área escura formada pela ausência ou interceptação da luz.", "Vulto ou imagem pouco nítida."]],
      ["Voz", ["Som produzido pelas cordas vocais humanas.", "Faculdade de falar.", "Opinião, voto."]],
      ["Silêncio", ["Ausência total de ruído ou som.", "Estado de quem se cala ou não fala."]],
      ["Música", ["Arte de combinar os sons de forma sucessiva e simultânea, com ordem e equilíbrio.", "Qualquer composição musical."]],
      ["Corpo", ["A parte material e física de um ser vivo.", "Conjunto de todas as partes de um organismo."]],
      ["Mente", ["Faculdade intelectual; o conjunto das atividades psíquicas e cognitivas.", "Pensamento, inteligência."]],
      ["Alma", ["Princípio espiritual ou imaterial do ser humano.", "A sede das emoções e sentimentos."]],
      ["Coração", ["Órgão muscular que bombeia o sangue.", "Sede simbólica dos sentimentos, especialmente do amor."]],
      ["Cérebro", ["Principal órgão do sistema nervoso, responsável pelo pensamento e controle do corpo.", "A mente, a inteligência."]],
      ["Mão", ["Parte terminal do braço humano, usada para pegar e segurar.", "Habilidade, destreza."]],
      ["Pé", ["Parte terminal da perna, que serve para a locomoção e sustentação.", "Base ou suporte de algo."]],
      ["Olho", ["Órgão da visão.", "Abertura, furo."]],
      ["Boca", ["Cavidade na face por onde se ingerem os alimentos e se emitem sons.", "Entrada ou abertura de algo."]],
      ["Mar", ["Grande extensão de água salgada que cobre a maior parte da Terra."]],
      ["Rio", ["Curso de água natural que deságua em outro rio, num lago ou no mar."]],
      ["Céu", ["Espaço infinito onde se movem os astros, visto da Terra como uma abóbada.", "Paraíso."]],
      ["Terra", ["O terceiro planeta do sistema solar.", "Solo, chão sobre o qual se pisa."]],
      ["Montanha", ["Grande elevação natural do terreno."]],
      ["Floresta", ["Grande extensão de terreno coberta de árvores; bosque."]],
      ["Árvore", ["Planta de grande porte, com tronco lenhoso que se ramifica em galhos."]],
      ["Flor", ["Parte da planta onde se encontram os órgãos reprodutores, geralmente colorida e perfumada."]],
      ["Animal", ["Ser vivo dotado de sensibilidade e movimento, que não é uma planta."]],
      ["Carro", ["Veículo motorizado de quatro rodas, para transporte de passageiros."]],
      ["Avião", ["Aeronave com asas e motores, mais pesada que o ar."]],
      ["Barco", ["Pequena embarcação para navegar na água."]],
      ["Trem", ["Veículo ferroviário composto por uma ou mais locomotivas e vagões."]],
      ["Caminho", ["Via por onde se transita; estrada.", "Direção, rumo, percurso."]],
      ["Porta", ["Abertura em uma parede que permite a entrada e saída.", "Meio de acesso a algo."]],
      ["Janela", ["Abertura na parede de um edifício para permitir a entrada de luz e ventilação."]],
      ["Chão", ["Superfície sobre a qual se pisa; solo, pavimento."]],
      ["Teto", ["Superfície interior e superior de um cômodo.", "Limite máximo de algo."]],
      ["Correr", ["Mover-se rapidamente, dando passos largos e acelerados.", "Passar rapidamente (o tempo)."]],
      ["Andar", ["Mover-se, dando passos; caminhar.", "Estar em certo estado ou condição."]],
      ["Ler", ["Percorrer com a visão um texto escrito, interpretando seu sentido.", "Interpretar, compreender."]],
      ["Escrever", ["Representar ideias ou palavras por meio de sinais gráficos.", "Compor uma obra."]],
      ["Cantar", ["Produzir sons melodiosos com a voz.", "Compor ou executar uma canção."]],
      ["Dançar", ["Mover o corpo em ritmo e cadência, geralmente ao som de música."]],
      ["Pensar", ["Formar ideias na mente; raciocinar, refletir.", "Ter a intenção de; planejar."]],
      ["Sentir", ["Perceber por meio dos sentidos.", "Experimentar uma emoção ou sensação."]],
      ["Olhar", ["Fixar a vista em; ver.", "Observar, examinar."]],
      ["Chorar", ["Derramar lágrimas em resposta a uma emoção.", "Lamentar-se."]],
      ["Rir", ["Contrair os músculos faciais em expressão de alegria ou zombaria, emitindo sons característicos."]],
      ["Brincar", ["Divertir-se, entreter-se com jogos ou passatempos infantis.", "Zombar, gracejar."]],
      ["Pintar", ["Cobrir uma superfície com tinta.", "Criar uma obra de arte com tintas."]],
      ["Desenhar", ["Representar formas ou figuras por meio de linhas e traços."]],
      ["Conversar", ["Falar com outra(s) pessoa(s); dialogar."]],
      ["Construir", ["Edificar, erguer uma obra de engenharia ou arquitetura.", "Criar, elaborar."]],
      ["Destruir", ["Arruinar, demolir.", "Aniquilar, exterminar."]],
      ["Dinheiro", ["Moeda corrente; meio de troca na forma de notas e moedas.", "Riqueza, fortuna."]],
      ["Governo", ["Órgão que dirige uma nação ou estado.", "Ato ou efeito de governar; administração."]],
      ["Lei", ["Norma ou conjunto de normas jurídicas criadas por uma autoridade soberana.", "Regra, preceito."]],
      ["Guerra", ["Conflito armado entre nações ou entre grupos dentro de uma mesma nação."]],
      ["Professor", ["Aquele que ensina uma arte, ciência ou disciplina.", "Pessoa que tem como profissão o ensino."]],
      ["Médico", ["Profissional autorizado a exercer a medicina.", "Pessoa que cuida da saúde das pessoas."]],
      ["Artista", ["Pessoa que pratica uma das belas-artes, especialmente pintura, escultura, música ou literatura."]],
      ["Cientista", ["Pessoa que se dedica à ciência e à pesquisa científica."]],
      ["Fogo", ["Fenômeno que resulta da combustão de matérias inflamáveis.", "Incêndio; paixão ardente."]],
      ["Vento", ["Ar em movimento na atmosfera."]],
      ["Chuva", ["Precipitação de gotas de água das nuvens para a Terra."]],
      ["Neve", ["Precipitação de cristais de gelo."]],
      ["Vermelho", ["A cor do sangue ou do rubi."]],
      ["Azul", ["A cor do céu diurno sem nuvens."]],
      ["Verde", ["A cor da vegetação fresca, como a grama."]],
      ["Amarelo", ["A cor do ouro ou do limão maduro."]],
      ["Branco", ["A cor da neve; a cor que reflete todos os raios do espectro luminoso."]],
      ["Preto", ["A cor do carvão; a ausência de cor ou luz."]],
      ["Pão", ["Alimento feito de farinha, água e fermento, cozido ao forno."]],
      ["Leite", ["Líquido branco produzido pelas fêmeas dos mamíferos para alimentar suas crias."]],
      ["Queijo", ["Alimento sólido ou pastoso obtido pela coagulação do leite."]],
      ["Fruta", ["Produto comestível de certas plantas, geralmente doce ou ácido."]],
      ["Jornal", ["Publicação periódica que contém notícias, artigos e anúncios.", "Telejornal."]],
      ["Internet", ["Rede mundial de computadores interligados que permite a comunicação e a troca de dados."]],
      ["Verdade", ["Aquilo que corresponde à realidade ou aos fatos.", "Proposição que não pode ser negada racionalmente."]],
      ["Mentira", ["Afirmação contrária à verdade com a intenção de enganar.", "Engano, ilusão, falsidade."]],
      ["Realidade", ["Qualidade do que é real; existência efetiva.", "O conjunto das coisas e fatos reais."]],
      ["Destino", ["Sequência de eventos considerados inevitáveis e predeterminados.", "O rumo ou fim da vida de alguém ou de algo."]],
      ["Consciência", ["Capacidade de perceber a própria existência e o ambiente ao redor.", "Noção do que é moralmente certo ou errado."]],
      ["Palavra", ["Unidade linguística com significado, composta por um ou mais fonemas.", "Promessa ou compromisso verbal."]],
      ["Idioma", ["Língua própria de uma nação ou povo.", "Sistema de signos usado por uma comunidade para se comunicar."]],
      ["Filosofia", ["Estudo de questões fundamentais sobre a existência, o conhecimento, os valores, a razão, a mente e a linguagem."]],
      ["Psicologia", ["Ciência que estuda os processos mentais e o comportamento humano."]],
      ["Empresa", ["Organização econômica que visa à produção ou venda de bens ou serviços, com o objetivo de lucro."]],
      ["Mercado", ["Lugar onde ocorrem as relações de troca e comércio.", "O conjunto de compradores e vendedores de um determinado bem."]],
      ["Cliente", ["Pessoa ou entidade que compra ou utiliza produtos ou serviços de uma empresa."]],
      ["Produto", ["Objeto ou serviço que é resultado de um processo de produção e que é oferecido em um mercado."]],
      ["Pai", ["Genitor do sexo masculino; homem que tem um ou mais filhos."]],
      ["Mãe", ["Genitora do sexo feminino; mulher que tem um ou mais filhos."]],
      ["Filho", ["Descendente em relação aos seus pais."]],
      ["Irmão", ["Pessoa que tem os mesmos pais que outra."]],
      ["Manhã", ["Período do dia que vai do amanhecer ao meio-dia."]],
      ["Tarde", ["Período do dia entre o meio-dia e o anoitecer."]],
      ["Noite", ["Período do dia compreendido entre o pôr do sol e o amanhecer."]],
      ["Cozinhar", ["Preparar alimentos para o consumo, geralmente usando calor.", "Elaborar, maquinar."]],
      ["Sal", ["Substância cristalina, branca, usada como tempero e para conservar alimentos; cloreto de sódio."]],
      ["Açúcar", ["Substância cristalina de sabor doce, extraída principalmente da cana-de-açúcar ou da beterraba."]],
      ["Algoritmo", ["Sequência finita de regras ou operações bem definidas para a solução de um problema."]],
      ["Nuvem", ["Massa visível de gotículas de água ou cristais de gelo suspensos na atmosfera.", "Em computação, rede de servidores para armazenamento e processamento de dados."]],
      ["Tempestade", ["Perturbação atmosférica violenta, com ventos fortes, chuva, raios e trovões."]],
])